# Generated by Django 4.2.5 on 2024-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('Bond', models.CharField(max_length=50)),
                ('industy_type', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Civil Engineering With Computer Applications', 'Civil Engineering With Computer Applications'), ('Robotics and Artificial Intelligence', 'Robotics and Artificial Intelligence'), ('Mechanical and Mechatronics Engineering (Additive Manufacturing)', 'Mechanical and Mechatronics Engineering (Additive Manufacturing)'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Computer Engineering', 'Electronics and Computer Engineering'), ('Electrical and Computer Engineering', 'Electrical and Computer Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering (Construction Technology)', 'Civil Engineering (Construction Technology)'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Artificial Intelligence and Data Science', 'Artificial Intelligence and Data Science'), ('Architecture', 'Architecture')], max_length=100)),
                ('job_role', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('job_eligibility', models.TextField()),
                ('selection_process', models.TextField()),
                ('job_CTC', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
