# Generated by Django 4.2.5 on 2024-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='comany_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
