# Generated by Django 4.2.5 on 2024-02-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0002_drive_comany_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='comany_logo',
            new_name='company_logo',
        ),
    ]
