# Generated by Django 4.2.5 on 2024-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0003_rename_comany_logo_drive_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
