# Generated by Django 4.2.5 on 2024-02-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0005_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='drive',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
