# Generated by Django 4.2.5 on 2024-02-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0006_alter_activity_options_alter_drive_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='company_name',
        ),
    ]
