# Generated by Django 4.2.5 on 2024-02-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0007_rename_name_activity_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='industy_type',
            new_name='industry_type',
        ),
    ]
