# Generated by Django 4.2.5 on 2024-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0008_rename_industy_type_drive_industry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='drive',
            name='department',
        ),
        migrations.AddField(
            model_name='drive',
            name='department',
            field=models.ManyToManyField(to='Notices.department'),
        ),
    ]
