# Generated by Django 4.2.5 on 2024-02-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0009_department_remove_drive_department_drive_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
