# Generated by Django 4.2.5 on 2024-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0010_alter_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='department',
        ),
        migrations.AddField(
            model_name='activity',
            name='department',
            field=models.ManyToManyField(to='Notices.department'),
        ),
    ]
